### ISSUE TITLE
clone无法使用

### ISSUE THREAD

**Issue by chauncey09** [WangNingkai/Lablog#2]
正克隆到 'tmp'...
fatal: 远程分支 release 在上游 origin 未发现
Unexpected end of command stream

**Comment by WangNingkai** [comment]
更换为github 仓库

**Comment by chauncey09** [comment]
尝试使用宝塔安装，前面没有问题
执行php artisan lablog:migrate时，出现错误：
  Illuminate\Database\QueryException  : SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) (SQL: select * from information_schema.tables where table_schema = lablog and table_name = migrations)

 660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 
请问是否需要手动创建数据库？

**Comment by chauncey09** [comment]
上述问题通过手动在宝塔面板建立数据解决了，执行完整安装命令后提示安装成功
Database seeding completed successfully.
========== 安装完成 ==========
更多配置项请访问根目录.env文件
访问域名时显示恭喜站点创建成功，请问下一步如何执行？

**Comment by WangNingkai** [comment]
解析站点域名到 项目public 目录

**Comment by chauncey09** [comment]
网站目录下运行目录无法选择/public?
之前安装OLAINDEX中可以选择，这个无法选择，请问如何解决呢？

**Comment by WangNingkai** [comment]
确保你拉取到正确的仓库了

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: chauncey09 <notifications@github.com>
发送时间: Sunday, December 9, 2018 5:21:49 PM
收件人: WangNingkai/Lablog
抄送: Wang Ningkai; Comment
主题: Re: [WangNingkai/Lablog] clone无法使用 (#2)


网站目录下运行目录无法选择/public?
之前安装OLAINDEX中可以选择，这个无法选择，请问如何解决呢？

―

**Comment by chauncey09** [comment]
拉去仓库地址如下：
git clone https://github.com/WangNingkai/Lablog.git tmp 
应该没有问题

**Comment by WangNingkai** [comment]
有public 目录就是对的，没有就是错的

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: chauncey09 <notifications@github.com>
发送时间: Sunday, December 9, 2018 5:27:04 PM
收件人: WangNingkai/Lablog
抄送: Wang Ningkai; Comment
主题: Re: [WangNingkai/Lablog] clone无法使用 (#2)


拉去仓库地址如下：
git clone https://github.com/WangNingkai/Lablog.git tmp
应该没有问题

―
